- name: "upgrade all packages"
  yum: name=* state=latest

- name: Install MySQL
  yum: name={{ item.name }} state=latest
  with_items:
    - { name: 'mysql' }
    - { name: 'mysql-server' }
    - { name: 'MySQL-python' }

- name: Start the MySQL service
  service: name={{ item.name }} enabled={{ item.chkconfig }} state={{ item.s }}
  with_items:
  - { name: 'mysqld', chkconfig: 'yes', s: 'started' }

# MySQLのrootのパスワードの変更
- mysql_user: name=root host={{item.name}} password={{ mysql_root_password }}
  with_items:
    - { name: "{{ ansible_hostname }}" }
    - { name: 127.0.0.1 }
    - { name: localhost }

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: delete anonymous MySQL server user for $server_hostname
  action: mysql_user user="" host="$server_hostname" state="absent"

- name: delete anonymous MySQL server user for localhost
  action: mysql_user user="" state="absent"

- name: remove the MySQL test database
  action: mysql_db db=test state=absent

- name: create wordpress database
  mysql_db: db={{ mysql_wordpress_dbname }} state=present encoding=utf8

- name: create wordpress database user
  mysql_user: name={{ item.n }} password={{ item.p }} priv={{ item.n }}.*:ALL state=present
  with_items:
    - { n: "{{ mysql_wordpress_dbuser }}", p: "{{ mysql_wordpress_password }}" }

- name: copy /etc/my.cnf file
  copy: src=my.cnf dest=/etc/my.cnf owner=root group=root mode=644 backup=yes
      
- name: Restart the MySQL service
  service: name=mysqld state=restarted
